[tool.poetry]
name = "groupchat"
version = "0.3.1"
description = ""
authors = ["Krystian Krakowski <kkrakowski22@gmail.com>"]
readme = "README.md"
packages = [{include = "group_chat.py"}]

[tool.poetry.dependencies]
python = "^3.9"
grpcio-tools = "^1.54.2"
protobuf = "^4.23.1"
google = "^3.0.0"
trustme = "^1.0.0"
types-protobuf = "^4.24.0.2"
grpc-stubs = "^1.53.0.2"
mypy-protobuf = "^3.4.0"
typer = "^0.9.0"

[tool.poetry.dev-dependencies]
mypy = "^1.3.0"

[tool.poetry.scripts]
group-chat = "group_chat:app"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
