[tool.poetry]
name = "groupchat"
version = "0.3.7"
description = ""
authors = ["Krystian Krakowski <kkrakowski22@gmail.com>"]
readme = "README.md"
packages = [{include = "group_chat.py"}]

[tool.poetry.dependencies]
python = "^3.12"
grpcio-tools = "^1.62.1"
protobuf = "^4.23.1"
google = "^3.0.0"
trustme = "^1.0.0"
types-protobuf = "^4.24.0.20240311"
grpc-stubs = "^1.53.0.2"
mypy-protobuf = "^3.4.0"
typer = "^0.12.3"

[tool.poetry.dev-dependencies]
mypy = "^1.9.0"

[tool.poetry.scripts]
group-chat = "group_chat:app"

[tool.poetry.group.dev.dependencies]
pre-commit = "^3.7.0"
isort = "^5.13.2"
black = "^24.4.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.isort]
profile = "black"
